global:
  resolve_timeout: 5m

route:
  receiver: local-webhook
  group_by:
    - alertname
    - service
    - severity
  group_wait: 5s
  group_interval: 15s
  repeat_interval: 2m

receivers:
  - name: local-webhook
    webhook_configs:
      - url: http://alert-webhook:8080/alertmanager
        send_resolved: true
